events {}

http {
  server {
    listen 80;

    # Auth Service
    location /auth/ {
      proxy_pass http://auth-service:3001/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Product Service
    location /products/ {
      proxy_pass http://product-service:3002/products/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Inventory Service
    location /inventory/ {
      proxy_pass http://inventory-service:3003/inventory/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Alert Service
    location /alerts/ {
      proxy_pass http://alert-service:3004/alerts/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Frontend
    location / {
      proxy_pass http://frontend:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
  proxy_pass http://auth-service:3001/health;
}
  }
}